### PR TITLE
Set Up ESLint and Fix Linting Problems

### LINKED ISSUE #66: Adding ESLint into the project
ESLint statically analyzes your code to quickly find problems. ESLint is built into most text editors and you can run ESLint as part of your continuous integration pipeline.

- [x] Configure ESLint
- [x] Configure integration of Jest and Prettier
- [x] Fix all current linting issues

### PR DESCRIPTION
**Pull request by lucas2005gao**
Eslint has been set up - with airbnb code styles. Prettier and Jest integration is also configured.

Usages: 
- `npm run lint` for linting
- `npm run lint:fix` for getting linter to automatically fix problems

### CODE REVIEW

File: src/assets/images/LoginImage.jsx [hunk 1]
```diff
@@ -1,5 +1,6 @@
 import React from "react";
 
+// eslint-disable-next-line no-unused-vars
 function LoginImage(props) {
```
Comment (lucas2005gao) [inline src/assets/images/LoginImage.jsx]: These Props are unused so I have disabled linting on this temporarily. I'm unsure why it's put there?

File: src/components/global/Task/Subtask.jsx [hunk 2]
```diff
@@ -10,10 +10,15 @@ function Subtask(props) {
   return (
     <div className="subtask-container">
       <div
-        className={"subtask-checkbox" + (isChecked ? "--checked" : "")}
+        className={`subtask-checkbox${  isChecked ? "--checked" : ""}`}
         onClick={handleCheckBoxClick}
+        onKeyDown={handleCheckBoxClick}
+        role="checkbox"
```
Comment (lucas2005gao) [inline src/components/global/Task/Subtask.jsx:16]: @thakurtushar02 A confirmation from you would be good since you implemented this component. Same applies to `src/components/global/IconButton.jsx` and `src/components/global/Task/Task.jsx`

File: src/assets/images/LoginImage.jsx (hunk 1 above)
Comment (yuno99825) [reply src/assets/images/LoginImage.jsx]: Can just remove the props

File: src/components/global/Task/Subtask.jsx (hunk 2 above)
Comment (yuno99825) [reply src/components/global/Task/Subtask.jsx:16]: I also implemented this. Why do we need these extra fields?

File: src/components/global/Task/Task.jsx [hunk 3]
```diff
@@ -12,20 +12,25 @@ function Task(props) {
...
 
   return (
-    <div className={"task-container" + (isExpanded ? "--expanded" : "")}>
+    <div className={`task-container${  isExpanded ? "--expanded" : ""}`}>
       <div className="task-header-container">
         <div
-          className={"task-checkbox" + (isChecked ? "--checked" : "")}
+          className={`task-checkbox${  isChecked ? "--checked" : ""}`}
           onClick={handleCheckBoxClick}
+          onKeyDown={handleCheckBoxClick}
```
Comment (yuno99825) [inline src/components/global/Task/Task.jsx:20]: why do we need these fields?

File: src/components/global/TextInput.jsx [hunk 4]
```diff
@@ -1,9 +1,12 @@
+import React from "react";
+
 function TextInput(props) {
   const { label, textValue, placeholderValue, onChangeHandler } = props;
   
   return (
     <div className="text-input">
       {label && 
+        // eslint-disable-next-line jsx-a11y/label-has-associated-control
```
Comment (yuno99825) [inline src/components/global/TextInput.jsx:9]: Why do we need this disable?

File: src/components/global/Task/Subtask.jsx (hunk 2 above)
Comment (lucas2005gao) [reply src/components/global/Task/Subtask.jsx:16]: It's from eslint(jsx-a11y/no-static-element-interactions) rule that: `Static HTML elements with event handlers require a role.`
Documentations can be found here: [Jsx-eslint](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/master/docs/rules/no-static-element-interactions.md)

File: src/components/global/Task/Task.jsx (hunk 3 above)
Comment (lucas2005gao) [reply src/components/global/Task/Task.jsx:20]: OnKeyDown is from this linting rule: [click-events-have-key-events](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/master/docs/rules/click-events-have-key-events.md)

**Review by yuno99825 — APPROVED** [review]
Looks good, up to you whether to keep those style rules.

**Review by YungiKim1999 — APPROVED** [review]
Great work~~

File: src/components/global/TextInput.jsx (hunk 4 above)
Comment (lucas2005gao) [reply src/components/global/TextInput.jsx:9]: I disabled it/didn't fix it as I don't know the context of this component (not being used yet). I will leave it disabled for now, @Angstylemon if you have free time you can look into this, cheers.

**Comment by lucas2005gao** [comment]
Hey team, for future reference: if you come across a linting error, please look into the problem, eslint gives you good suggestions upon hovering over the problems. 
If you think it's suitable you can disable it for the line to disable the rule, (hover over the code -> Quick Fix -> disable for this line). 
If you think the rule should be removed project-wide then put it into .eslintrc.js. Cheers
